// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YeminusSoftware.Infrastructure.Data;

#nullable disable

namespace YeminusSoftware.Infrastructure.Migrations
{
    [DbContext(typeof(YeminusSoftwareContext))]
    partial class YeminusSoftwareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YeminusSoftware.Domain.Product", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("ForSale")
                        .HasColumnType("boolean");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("text");

                    b.Property<string>("PriceList")
                        .HasColumnType("text");

                    b.Property<int?>("Vat")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            Description = "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
                            ForSale = true,
                            ImgUrl = "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
                            PriceList = "[]",
                            Vat = 19
                        },
                        new
                        {
                            Code = 2,
                            Description = "Mens Casual Premium Slim Fit T-Shirts",
                            ForSale = true,
                            ImgUrl = "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
                            PriceList = "[]",
                            Vat = 19
                        },
                        new
                        {
                            Code = 3,
                            Description = "Mens Cotton Jacket",
                            ForSale = true,
                            ImgUrl = "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
                            PriceList = "[5000]",
                            Vat = 19
                        },
                        new
                        {
                            Code = 4,
                            Description = "Mens Casual Slim Fit",
                            ForSale = true,
                            ImgUrl = "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
                            PriceList = "[50000]",
                            Vat = 19
                        },
                        new
                        {
                            Code = 5,
                            Description = "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
                            ForSale = true,
                            ImgUrl = "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
                            PriceList = "[50400]",
                            Vat = 19
                        },
                        new
                        {
                            Code = 6,
                            Description = "Solid Gold Petite Micropave",
                            ForSale = true,
                            ImgUrl = "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
                            PriceList = "[4500]",
                            Vat = 19
                        },
                        new
                        {
                            Code = 7,
                            Description = "White Gold Plated Princess",
                            ForSale = true,
                            ImgUrl = "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
                            PriceList = "[95000]",
                            Vat = 19
                        },
                        new
                        {
                            Code = 8,
                            Description = "Pierced Owl Rose Gold Plated Stainless Steel Double",
                            ForSale = true,
                            ImgUrl = "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
                            PriceList = "[36800]",
                            Vat = 19
                        },
                        new
                        {
                            Code = 9,
                            Description = "WD 2TB Elements Portable External Hard Drive - USB 3.0",
                            ForSale = true,
                            ImgUrl = "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
                            PriceList = "[89000]",
                            Vat = 19
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
